SumSquareDifference : SumSquareDifference.o
	g++ -Wall -o SumSquareDifference SumSquareDifference.o

SumSquareDifference.o : SumSquareDifference.cpp
	g++ -Wall -c -std=c++11 SumSquareDifference.cpp

clean:
	rm SumSquareDifference.o SumSquareDifference
