Multiples3and5 : Multiples3and5.o
	g++ -Wall -o Multiples3and5 Multiples3and5.o

Multiples3and5.o : Multiples3and5.cpp
	g++ -Wall -c -std=c++11 Multiples3and5.cpp

clean:
	rm Multiples3and5 Multiples3and5.o
