HighlyDivisibleTriangularNum : HighlyDivisibleTriangularNum.o
	g++ -Wall -o HighlyDivisibleTriangularNum HighlyDivisibleTriangularNum.o

HighlyDivisibleTriangularNum.o : HighlyDivisibleTriangularNum.cpp
	g++ -Wall -c -std=c++11 HighlyDivisibleTriangularNum.cpp

clean:
	rm HighlyDivisibleTriangularNum.o HighlyDivisibleTriangularNum
