SmallestMultiple : SmallestMultiple.o
	g++ -Wall -o SmallestMultiple SmallestMultiple.o

SmallestMultiple.o : SmallestMultiple.cpp
	g++ -Wall -c -std=c++11 SmallestMultiple.cpp

clean:
	rm SmallestMultiple.o SmallestMultiple
