LargestProdInSeries : LargestProdInSeries.o
	g++ -Wall -o LargestProdInSeries LargestProdInSeries.o

LargestProdInSeries.o : LargestProdInSeries.cpp ../ConvenientHeaderFiles/printVector.h ../ConvenientHeaderFiles/returnLargestInVector.h
	g++ -Wall -c -std=c++11 LargestProdInSeries.cpp

clean:
	rm LargestProdInSeries LargestProdInSeries.o
