# TODO: create this Makefile

# It is likely that defulat C compiler is already gcc, but be explicit anyway
#CC = gcc

# The CFLAGS variable sets the flags for the compiler.  CS107 adds these flags:
#  -g          compile with debug information
#  -O0         do not optimize generated code
#  -std=gnu99  use the C99 standard language definition with GNU extensions
#  -W<various> configures which diagnostic warnings are given
#CFLAGS = -g -O0 -std=gnu99 -Wall $$warnflags
#export warnflags = -Wfloat-equal -Wtype-limits -Wpointer-arith -Wlogical-op -Wshadow -fno-diagnostics-show-option

LatticePaths.o : LatticePaths.c
    gcc -c
