LargestProdInGrid : LargestProdInGrid.o
	g++ -Wall -o LargestProdInGrid LargestProdInGrid.o

LargestProdInGrid.o : LargestProdInGrid.cpp
	g++ -Wall -c -std=c++11 LargestProdInGrid.cpp

clean:
	rm LargestProdInGrid.o LargestProdInGrid
