1001stPrime : 1001stPrime.o
	g++ -Wall -o 1001stPrime 1001stPrime.o

1001stPrime.o : 1001stPrime.cpp printVector.h isPrime.h
	g++ -Wall -c -std=c++11 1001stPrime.cpp

clean:
	rm 1001stPrime.o 1001stPrime
