truncatableprimes : truncatableprimes.o
	g++ -Wall -o truncatableprimes truncatableprimes.o

truncatableprimes.o : truncatableprimes.cpp
	g++ -Wall -c -std=c++11 truncatableprimes.cpp

clean:
	rm truncatableprimes.o truncatableprimes
