LargestPalindromeProduct : LargestPalindromeProduct.o
	g++ -Wall -o LargestPalindromeProduct LargestPalindromeProduct.o

LargestPalindromeProduct.o : LargestPalindromeProduct.cpp
	g++ -Wall -c -std=c++11 LargestPalindromeProduct.cpp

clean:
	rm LargestPalindromeProduct.o LargestPalindromeProduct
